R710:
  hostname: R710
  march: westmere
  cpu_flags_x86: aes avx f16c mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3
  features:
    - docker
  makeopts: 16
  video_cards: intel
  network_interface: eno1
  kernel_fragments:
    - docker
    - gvt
    - kvm
    - libvirt
XPS-9700:
  hostname: XPS-9700
  march: skylake
  cpu_flags_x86: aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3
  features:
    - X
    - docker
    - audio
    - wifi
  makeopts: 16
  video_cards: intel
  network_interface: wlp4s0
  kernel_fragments:
    - docker
    - gvt
    - kvm
    - libvirt
    - bluez
XPS-9730:
  hostname: XPS-9730
  march: skylake
  cpu_flags_x86: aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 ssse3
  features:
    - X
    - docker
    - audio
    - wifi
    - steam
    - bluetooth
  makeopts: 16
  video_cards: intel
  network_interface: eno1
  kernel_fragments:
    - docker
    - gvt
    - kvm
    - libvirt
    - bluez
